language: android
jdk: oraclejdk8
sudo: required
dist: precise # For 7.5GB of memory since the emulator requires a big chunk.
env:
  matrix:
    - ANDROID_TARGET=android-23
  global:
    - ADB_INSTALL_TIMEOUT=12
android:
  components:
    # use the latest revision of Android SDK Tools
    - platform-tools
    - tools

    # The BuildTools version used
    - build-tools-23.0.3

    # The SDK version used to compile the project
    - android-23

    # Additional components
    - extra-google-m2repository
    - extra-android-m2repository

notifications:
  email: true

before_script:
  - git fetch --tags
  - git fetch --unshallow || true
  - export DESCRIBE=$(git describe)
  - export PR=https://api.github.com/repos/$TRAVIS_REPO_SLUG/pulls/$TRAVIS_PULL_REQUEST
  - export BRANCH=$(if [ "$TRAVIS_PULL_REQUEST" == "false" ]; then echo $TRAVIS_BRANCH; else echo `curl -s $PR | jq -r .head.ref`; fi)
  - echo "TRAVIS_BRANCH=$TRAVIS_BRANCH, PR=$PR, BRANCH=$BRANCH, DESCRIBE=$DESCRIBE"
  - chmod +x gradlew
  # Begin spinning up an emulator in the background
  - make emulator

script:
  - make quality
  - make test
  # Check if emulator has finished booting
  - android-wait-for-emulator
  - adb shell input keyevent 82 &
  - travis_wait make e2e

after_script:
  - make artifacts
  - mv OpenEdXMobile/screenshots artifacts/
  - curl -sL https://raw.githubusercontent.com/travis-ci/artifacts/master/install | bash
  - ~/bin/artifacts upload artifacts

branches:
  only:
    - master

# Enable caching to speed up the build
cache:
  directories:
    - $HOME/.gradle

before_install:
  - pip install --user codecov
  - pip install --user pillow # For screenshot tests
after_success:
  - codecov
