name: Android CI
on: [push]

env:
  SAMPLE_PATH: EdX

jobs:
  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy C! gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Build Project
        working-directory: ${{ env.SAMPLE_PATH }}
        run: .gradlew assembledebug

      - name: Upload build ouputs (APKS)
        uses: actions/upload-artifact@v2
        with:
          name: build-outputs
          path: ${{ env.SAMPLE_PATH }}/app/build/outputs

  test:
    needs: build
    runs-on: macos-latest
    timeout-minutes: 30
    strategy:
      matrix:
        api-level: [24, 27, 30]

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Copy CI gradle.properties
        run: mkdir -p ~/.gradle ; cp .github/ci-gradle.properties ~/.gradle/gradle.properties

      - name: set up JDK 8
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: '8'

      - name: Run tests
        uses: actions/android-emulator-runner@v2
        with:
          api-level: ${{ matrix.api-level }}
          arch: x86
          disable-animations: true
          script: ./gradlew jacocoTestProdDebugUnitTestReport
          working-directory: ${{ env.SAMPLE_PATH }}
